server {
    listen 80;
    server_name localhost;

    # Aumenta o tamanho máximo de upload para aceitar os áudios do Whisper
    client_max_body_size 20M;

    location / {
        proxy_pass http://api_tcc:8000; # "api_tcc" será o nome do serviço no Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts longos para a IA processar sem derrubar a conexão
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
    }
}